apiVersion: v1
kind: Service
metadata:
  name: {{ include "oracle11.fullname" . }}
  labels:
    {{- include "oracle11.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service2.port }}
      targetPort: {{ .Values.service2.port }}
      protocol: TCP
      name: db
  selector:
    {{- include "oracle11.selectorLabels" . | nindent 4 }}
